CREATE TABLE IF NOT EXISTS customers (
   id uuid NOT NULL CONSTRAINT customers_pk PRIMARY KEY,
   first_name VARCHAR(20) NOT NULL,
   middle_name VARCHAR(20) NOT NULL,
   last_name VARCHAR(20) NOT NULL,
   gender VARCHAR(20),
   dob DATE NOT NULL,
   email VARCHAR(30) NOT NULL UNIQUE,
   phone VARCHAR(12) NOT NULL UNIQUE,
   id_number VARCHAR(30),
   loan_limit DECIMAL(12, 2) NOT NULL,
   account_status VARCHAR(20) NOT NULL,
   billing_cycle VARCHAR(20) NOT NULL,
   preferred_billing_day INT,
   description VARCHAR(255),
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   created_by VARCHAR(36),
   updated_by VARCHAR(36)
);